# Generated by Django 4.1 on 2022-08-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Member', 'Member'), ('Librarian', 'Librarian')], default='mem', max_length=20),
        ),
    ]
